version: '3'
services:
  selenium-hub:
    image: selenium/hub:4.0.0
    ports:
      - "4444:4444"

  chrome-node:
    image: selenium/node-chrome:4.0.0
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  firefox-node:
    image: selenium/node-firefox:4.0.0
    depends_on:
      - selenium-hub
      - chrome-node
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444